import {
  Activity,
  Anchor,
  Antenna,
  Armchair,
  Award,
  Baby,
  Bath,
  BedDouble,
  Bell,
  Bike,
  Blinds,
  Blocks,
  Box,
  Building,
  Building2,
  Cable,
  Camera,
  Car,
  Castle,
  Church,
  Cloud,
  CookingPot,
  Cog,
  Compass,
  Construction,
  Container,
  Crown,
  Diamond,
  DoorOpen,
  Drill,
  Droplets,
  Dumbbell,
  Fan,
  Fence,
  Fingerprint,
  Flag,
  Flame,
  Flower2,
  Grid3x3,
  Hammer,
  HardHat,
  Home,
  Hotel,
  Key,
  Lamp,
  LampDesk,
  Landmark,
  Layers,
  LayoutGrid,
  LayoutTemplate,
  Leaf,
  Lightbulb,
  Lock,
  Map as MapIcon,
  MapPin,
  Mountain,
  Music,
  Package,
  PaintBucket,
  Paintbrush,
  Palette,
  PanelTop,
  Plug,
  Refrigerator,
  Ruler,
  Router,
  Sailboat,
  School,
  Scissors,
  Settings,
  Shield,
  ShowerHead,
  Shovel,
  Snowflake,
  Sofa,
  Sprout,
  Star,
  Store,
  Sun,
  Sunrise,
  Tent,
  Thermometer,
  Toilet,
  Tractor,
  TreeDeciduous,
  TreePine,
  Trees,
  Truck,
  Tv,
  Umbrella,
  Users,
  Warehouse,
  WashingMachine,
  Waves,
  Wifi,
  Wind,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export interface CategoryIconEntry {
  name: string;
  icon: LucideIcon;
  keywords: string;
}

/** Curated library shown in the category icon picker (search matches name + keywords). */
export const ICON_LIBRARY: CategoryIconEntry[] = [
  { name: "Home", icon: Home, keywords: "house dwelling residence building" },
  { name: "Building2", icon: Building2, keywords: "addition apartment office tower" },
  { name: "Hammer", icon: Hammer, keywords: "demolition tool construction repair" },
  { name: "DoorOpen", icon: DoorOpen, keywords: "door window entry" },
  { name: "Zap", icon: Zap, keywords: "generator electric power energy" },
  { name: "Grid3x3", icon: Grid3x3, keywords: "screen enclosure cage mesh grid" },
  { name: "Layers", icon: Layers, keywords: "deck driveway pavement surface" },
  { name: "Shield", icon: Shield, keywords: "shutters hurricane protection security" },
  { name: "Waves", icon: Waves, keywords: "pool water swim" },
  { name: "Warehouse", icon: Warehouse, keywords: "roof storage garage" },
  { name: "Fence", icon: Fence, keywords: "fence gate wall boundary" },
  { name: "PaintBucket", icon: PaintBucket, keywords: "paint color exterior" },
  { name: "Trees", icon: Trees, keywords: "landscaping trees garden" },
  { name: "Sun", icon: Sun, keywords: "solar sun light" },
  { name: "Wrench", icon: Wrench, keywords: "repair maintenance tool" },
  { name: "Ruler", icon: Ruler, keywords: "measure survey plan" },
  { name: "Activity", icon: Activity, keywords: "pulse fitness" },
  { name: "Anchor", icon: Anchor, keywords: "dock marine boat" },
  { name: "Antenna", icon: Antenna, keywords: "antenna satellite tower" },
  { name: "Armchair", icon: Armchair, keywords: "furniture interior seat" },
  { name: "Award", icon: Award, keywords: "award prize" },
  { name: "Baby", icon: Baby, keywords: "child play" },
  { name: "Bath", icon: Bath, keywords: "bathroom bathtub" },
  { name: "BedDouble", icon: BedDouble, keywords: "bedroom bed" },
  { name: "Bell", icon: Bell, keywords: "alarm doorbell" },
  { name: "Bike", icon: Bike, keywords: "bicycle" },
  { name: "Blinds", icon: Blinds, keywords: "blinds shades window covering" },
  { name: "Blocks", icon: Blocks, keywords: "brick blocks masonry" },
  { name: "Box", icon: Box, keywords: "shed storage box" },
  { name: "Building", icon: Building, keywords: "commercial building" },
  { name: "Cable", icon: Cable, keywords: "cable wiring" },
  { name: "Camera", icon: Camera, keywords: "camera security surveillance" },
  { name: "Car", icon: Car, keywords: "car garage carport parking" },
  { name: "Castle", icon: Castle, keywords: "tower turret castle" },
  { name: "Church", icon: Church, keywords: "chapel" },
  { name: "Cloud", icon: Cloud, keywords: "weather cloud" },
  { name: "CookingPot", icon: CookingPot, keywords: "kitchen outdoor kitchen cooking" },
  { name: "Cog", icon: Cog, keywords: "mechanical equipment gear" },
  { name: "Compass", icon: Compass, keywords: "compass direction" },
  { name: "Construction", icon: Construction, keywords: "construction site barrier" },
  { name: "Container", icon: Container, keywords: "container dumpster" },
  { name: "Crown", icon: Crown, keywords: "premium crown" },
  { name: "Diamond", icon: Diamond, keywords: "premium diamond" },
  { name: "Drill", icon: Drill, keywords: "drill install tool" },
  { name: "Droplets", icon: Droplets, keywords: "irrigation sprinkler water drainage" },
  { name: "Dumbbell", icon: Dumbbell, keywords: "gym fitness" },
  { name: "Fan", icon: Fan, keywords: "fan ventilation hvac" },
  { name: "Fingerprint", icon: Fingerprint, keywords: "access lock biometric" },
  { name: "Flag", icon: Flag, keywords: "flag pole" },
  { name: "Flame", icon: Flame, keywords: "fire pit fireplace grill" },
  { name: "Flower2", icon: Flower2, keywords: "flowers garden plants" },
  { name: "HardHat", icon: HardHat, keywords: "contractor builder safety" },
  { name: "Hotel", icon: Hotel, keywords: "guest house hotel" },
  { name: "Key", icon: Key, keywords: "key access" },
  { name: "Lamp", icon: Lamp, keywords: "lamp lighting" },
  { name: "LampDesk", icon: LampDesk, keywords: "lighting fixture" },
  { name: "Landmark", icon: Landmark, keywords: "clubhouse landmark columns" },
  { name: "LayoutGrid", icon: LayoutGrid, keywords: "grid layout pavers tiles" },
  { name: "LayoutTemplate", icon: LayoutTemplate, keywords: "template form default" },
  { name: "Leaf", icon: Leaf, keywords: "leaf eco green" },
  { name: "Lightbulb", icon: Lightbulb, keywords: "lighting light bulb landscape lighting" },
  { name: "Lock", icon: Lock, keywords: "lock security" },
  { name: "Map", icon: MapIcon, keywords: "map survey plat" },
  { name: "MapPin", icon: MapPin, keywords: "location lot address" },
  { name: "Mountain", icon: Mountain, keywords: "grade terrain slope" },
  { name: "Music", icon: Music, keywords: "sound audio speaker" },
  { name: "Package", icon: Package, keywords: "package delivery box" },
  { name: "Paintbrush", icon: Paintbrush, keywords: "paint brush touch-up" },
  { name: "Palette", icon: Palette, keywords: "palette color scheme" },
  { name: "PanelTop", icon: PanelTop, keywords: "awning canopy panel" },
  { name: "Plug", icon: Plug, keywords: "ev charger outlet plug" },
  { name: "Refrigerator", icon: Refrigerator, keywords: "appliance kitchen" },
  { name: "Router", icon: Router, keywords: "network internet router" },
  { name: "Sailboat", icon: Sailboat, keywords: "boat marine" },
  { name: "School", icon: School, keywords: "school community" },
  { name: "Scissors", icon: Scissors, keywords: "trim cut hedge" },
  { name: "Settings", icon: Settings, keywords: "settings general" },
  { name: "ShowerHead", icon: ShowerHead, keywords: "shower outdoor shower" },
  { name: "Shovel", icon: Shovel, keywords: "dig excavation grading" },
  { name: "Snowflake", icon: Snowflake, keywords: "cooling ac air conditioner" },
  { name: "Sofa", icon: Sofa, keywords: "patio lanai furniture" },
  { name: "Sprout", icon: Sprout, keywords: "plants sprout lawn" },
  { name: "Star", icon: Star, keywords: "star favorite" },
  { name: "Store", icon: Store, keywords: "store shop" },
  { name: "Sunrise", icon: Sunrise, keywords: "sunrise sunroom" },
  { name: "Tent", icon: Tent, keywords: "tent pergola gazebo cabana" },
  { name: "Thermometer", icon: Thermometer, keywords: "temperature heat pump" },
  { name: "Toilet", icon: Toilet, keywords: "plumbing restroom" },
  { name: "Tractor", icon: Tractor, keywords: "equipment tractor" },
  { name: "TreeDeciduous", icon: TreeDeciduous, keywords: "tree removal tree" },
  { name: "TreePine", icon: TreePine, keywords: "pine tree" },
  { name: "Truck", icon: Truck, keywords: "truck delivery hauling" },
  { name: "Tv", icon: Tv, keywords: "outdoor tv media" },
  { name: "Umbrella", icon: Umbrella, keywords: "umbrella shade" },
  { name: "Users", icon: Users, keywords: "community group event" },
  { name: "WashingMachine", icon: WashingMachine, keywords: "laundry appliance" },
  { name: "Wifi", icon: Wifi, keywords: "wifi internet" },
  { name: "Wind", icon: Wind, keywords: "wind ventilation" },
];

/** Shown first in the picker, before the resident searches for more. */
export const SUGGESTED_ICON_NAMES = [
  "Home",
  "Building2",
  "Hammer",
  "DoorOpen",
  "Zap",
  "Shield",
  "Waves",
  "Warehouse",
  "Fence",
  "PaintBucket",
  "Trees",
  "Sun",
  "Wrench",
  "Ruler",
  "Car",
  "Lightbulb",
];

/** Used whenever a category has no icon selected. */
export const DEFAULT_CATEGORY_ICON = LayoutTemplate;

const BY_NAME = new Map(ICON_LIBRARY.map((e) => [e.name, e.icon]));

export function getCategoryIcon(name: string): LucideIcon {
  return BY_NAME.get(name) ?? DEFAULT_CATEGORY_ICON;
}
